[project]
name = "kakaw"
version = "0.1.0"
description = "Midterm Project for Artificial Intelligence Concepts Course 2026/2027"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
kakaw = "kakaw:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
